[package]
name = "miq-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
# GUI lib and extra widgets
eframe = "0.34.2"
egui_extras = "0.34.2"
# Logging interface, to stdout/err
log = "0.4.29"
env_logger = "0.11.10"
# MIDI
midir = "0.11.0"
# De/Serialization
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.1"
# File dialog
rfd = "0.17.2"
# Web
wasm-bindgen-futures = "0.4.72"
# Util
take_mut = "0.2.2" # temporarily take ownership from behind an &mut
pollster = "0.4.0" # un-async a future
